//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CobFullClaroMax_Sum
    {
        public string Conta { get; set; }
        public string Mês { get; set; }
        public string Telefone { get; set; }
        public string Nome { get; set; }
        public string Nickname { get; set; }
        public string CPF_Foneclube { get; set; }
        public string Plano_Foneclube { get; set; }
        public string Plano_Contratado { get; set; }
        public Nullable<double> Preço_único { get; set; }
        public Nullable<double> Fração_preço_único_por_linha { get; set; }
        public Nullable<decimal> Preço_Plano_FC { get; set; }
        public int Sem_uso { get; set; }
        public Nullable<double> Valor_cobrado_operadora { get; set; }
        public Nullable<double> Valor_total_com_excedentes_FC { get; set; }
        public Nullable<double> Resultado___linha { get; set; }
        public Nullable<int> Franquia_minutos { get; set; }
        public Nullable<int> Total_franquia_minutos { get; set; }
        public Nullable<int> Minutos_locais_excedentes { get; set; }
        public Nullable<int> C_Total_min__lig__Local_ { get; set; }
        public Nullable<int> C_Total_min__lig__Local_Tarifa_Zero_ { get; set; }
        public Nullable<decimal> C_Total_minutos_lig__p_números_especiais_ { get; set; }
        public Nullable<int> C_Total_ligações_Interurbanas_ { get; set; }
        public Nullable<int> C_Total_ligações_no_exterior_ { get; set; }
        public string Separador { get; set; }
        public Nullable<double> Valor_Ligações_Locais_oper_ { get; set; }
        public Nullable<double> Liga__es_para_n_meros_especiais { get; set; }
        public Nullable<double> Servi_os__Torpedos__Hits__Jogos__etc__ { get; set; }
        public Nullable<double> Interurbanas_e_Rec__em_viagem_21___Embratel { get; set; }
        public Nullable<double> Interurbanas_e_Rec__em_viagem_31___Telemar { get; set; }
        public Nullable<double> Liga__es_e_Servi_os_no_exterior { get; set; }
        public Nullable<double> Outros { get; set; }
        public Nullable<double> Multa { get; set; }
        public string Erro_valor_internet_operadora { get; set; }
        public string Plano_internet_desconhecido { get; set; }
        public Nullable<double> Mensalidades_e_Pacotes_Promocionais { get; set; }
        public Nullable<double> Valor_Total_a_Cobrar_do_Cliente { get; set; }
        public Nullable<double> Valor_Total_a_Cobrar_da_Linha_Equalizado { get; set; }
        public Nullable<int> Report_Month { get; set; }
        public Nullable<int> Report_Year { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public string MasterPlan { get; set; }
        public Nullable<decimal> C_TM__DDD { get; set; }
        public Nullable<decimal> Franquia_DDD { get; set; }
        public Nullable<decimal> Franquia_Local { get; set; }
        public Nullable<decimal> C_TM__Excedente_DDD { get; set; }
        public Nullable<decimal> C_TM__Locais_Excedentes { get; set; }
        public Nullable<decimal> Total_____Correto_Ligaçoes_DDD { get; set; }
        public Nullable<decimal> Total_____Correto_Ligaçoes_Locais { get; set; }
        public Nullable<decimal> C_T_Excedentes { get; set; }
        public Nullable<int> ContaID { get; set; }
        public string Active { get; set; }
        public string PDF { get; set; }
        public Nullable<decimal> PreçoVip { get; set; }
        public Nullable<double> C__T__Cobrar_Linha { get; set; }
        public Nullable<decimal> Assin_Contrato { get; set; }
        public string Portability { get; set; }
        public string Plano_Vivo_Old { get; set; }
    }
}
