//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CobFullVivo_Sum
    {
        public string Conta { get; set; }
        public string Data_Emissão { get; set; }
        public string Telefone { get; set; }
        public string CentroCusto { get; set; }
        public string Nome { get; set; }
        public string CPF_foneclube { get; set; }
        public string Cliente { get; set; }
        public string Nickname_foneclube { get; set; }
        public string Resultado___da_linha { get; set; }
        public string C__T__Valor_Total_a_Cobrar_cliente { get; set; }
        public string Valor_FC_Total_a_cobrar_da_linha { get; set; }
        public Nullable<decimal> Valor_Total_Cobrado_Vivo__com_desconto_ { get; set; }
        public Nullable<decimal> Preço_único { get; set; }
        public Nullable<double> C__T__Valor_Excedente_Total_Cliente_ { get; set; }
        public Nullable<double> C__T__Valor_Excedente_Servicos_Cliente { get; set; }
        public Nullable<double> Excedente_Por_linha_FC { get; set; }
        public string C_Sem_uso_ { get; set; }
        public Nullable<double> C__T__Valor_Excedentes_Minutos_Locais_Cliente { get; set; }
        public Nullable<double> C_T__Minutos_Locais_Cliente { get; set; }
        public Nullable<double> C__T__Excedentes_Minutos_Locais_Cliente { get; set; }
        public Nullable<int> C__T__Franquia_minutos_Local_Cliente_ { get; set; }
        public Nullable<double> Preço_FC { get; set; }
        public string Plano_FC { get; set; }
        public string Planos_divergentes { get; set; }
        public string Plano_FC_cadastrado { get; set; }
        public string Plano_Contratado_Vivo { get; set; }
        public Nullable<double> Preço_único_fração { get; set; }
        public Nullable<decimal> Valor_Total_Cobrado_Vivo__sem_desconto_ { get; set; }
        public string Valor_Total_Serviços { get; set; }
        public string Valor_Líquido_Serviços { get; set; }
        public Nullable<decimal> Valor_Total_Equipamento { get; set; }
        public string Plano_Duplicado { get; set; }
        public Nullable<double> Franquia_Total { get; set; }
        public Nullable<double> Franquia_Local { get; set; }
        public Nullable<decimal> Duracao_Total_local { get; set; }
        public Nullable<double> Excedente_franquia_local { get; set; }
        public Nullable<double> Valor_Excedente_franquia_local { get; set; }
        public Nullable<double> Valor_equalizado_franquia_local { get; set; }
        public decimal Valor_Cobrado_Local { get; set; }
        public Nullable<decimal> Duração_Minutos_Local { get; set; }
        public Nullable<decimal> Valor_Unitário_Cobrado_Local { get; set; }
        public Nullable<decimal> Duraçao_Min__Loc__Per_Anteriores { get; set; }
        public Nullable<double> Valor_cobrado_Minutos_Loc__Per_Anteriores { get; set; }
        public decimal Valor_Cobrado_DDD { get; set; }
        public Nullable<decimal> Duração_Minutos_DDD { get; set; }
        public Nullable<decimal> Valor_Unitário_Cobrado_DDD { get; set; }
        public Nullable<decimal> Duraçao_Min__DDD_Per_Anteriores { get; set; }
        public Nullable<double> Valor_cobrado_Minutos_DDD_Per_Anteriores { get; set; }
        public Nullable<decimal> Uso_Intra_Grupo { get; set; }
        public Nullable<decimal> Valor_Auditoria_Internet { get; set; }
        public decimal Valor_Serviço_Internet { get; set; }
        public decimal Valor_Desconto_Internet { get; set; }
        public Nullable<decimal> Valor_Líquido_Internet { get; set; }
        public decimal Valor_Contratado_Internet { get; set; }
        public int Quantidade_de_SMS { get; set; }
        public decimal Valor_Total_Cobrado_SMS { get; set; }
        public Nullable<decimal> Valor_Unitário_Cobrado_SMS { get; set; }
        public decimal Valor_Unitário_Contratado_SMS { get; set; }
        public Nullable<decimal> Valor_Unitário_Auditoria_SMS { get; set; }
        public int Qtd_SMS_Per_Ant { get; set; }
        public Nullable<double> Valor_SMS_Per_Ant_ { get; set; }
        public string Resultado___da_Cliente { get; set; }
        public Nullable<decimal> SMS_Amount { get; set; }
        public Nullable<int> Report_Month { get; set; }
        public Nullable<int> Report_Year { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public string Active { get; set; }
        public string PDF { get; set; }
        public string Portability { get; set; }
        public string Plano_Claro_Old { get; set; }
    }
}
