//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgGridState
    {
        public int intId { get; set; }
        public string txtStateName { get; set; }
        public string txtAgidName { get; set; }
        public string txtColumnState { get; set; }
        public string txtFilterModel { get; set; }
        public string txtSortModel { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    }
}
