//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBonusOrder
    {
        public int intIdComissionOrder { get; set; }
        public Nullable<int> intIdChargingHistory { get; set; }
        public Nullable<int> intIdTransaction { get; set; }
        public Nullable<int> intIdCustomerReceiver { get; set; }
        public Nullable<int> intIdPhone { get; set; }
        public Nullable<int> intIdPhonePlan { get; set; }
        public Nullable<int> intPercentBonus { get; set; }
        public Nullable<int> intIdAgent { get; set; }
        public bool bitComissionConceded { get; set; }
        public Nullable<System.DateTime> dteValidity { get; set; }
        public Nullable<System.DateTime> dteConceded { get; set; }
        public System.DateTime dteCreated { get; set; }
        public Nullable<int> intAmount { get; set; }
    }
}
