//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBonusOrderLog
    {
        public int intId { get; set; }
        public System.DateTime dteRegister { get; set; }
        public string txtLinhasAptasLiberarBonus { get; set; }
        public string txtLinhasMalComportamento { get; set; }
        public string txtLinhasPendentePagamento { get; set; }
        public string txtLlientesSemPaiQueNaoRecemBonus { get; set; }
        public string txtOrdensBonusLiberadas { get; set; }
        public string txtLinhasSemEvento { get; set; }
        public string txtLinhasComErroAoSalvar { get; set; }
    }
}
