//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBilhetacoesFebraban
    {
        public int intId { get; set; }
        public Nullable<int> intContaId { get; set; }
        public string txtControleSequencial { get; set; }
        public string txtVencimento { get; set; }
        public string txtEmissao { get; set; }
        public string txtIDUnicoNRC { get; set; }
        public string txtRecursoCNL { get; set; }
        public string txtDDD { get; set; }
        public string txtNumeroTelefone { get; set; }
        public string txtCaracteristicaRecurso { get; set; }
        public string txtDegrauRecurso { get; set; }
        public string txtDataLigacao { get; set; }
        public string txtCNLLocalidadeChamada { get; set; }
        public string txtNomeLocalidadeChamada { get; set; }
        public string txtUFTelefoneChamado { get; set; }
        public string txtCODNacionalInternacional { get; set; }
        public string txtCODOperadora { get; set; }
        public string txtDescricaoOperadora { get; set; }
        public string txtCODPais { get; set; }
        public string txtAreaDDD { get; set; }
        public string txtNumeroTelefoneChamado { get; set; }
        public string txtConjugadoNumeroTelefoneChamado { get; set; }
        public string txtDuracaoLigacao { get; set; }
        public string txtCategoria { get; set; }
        public string txtDescricaoCategoria { get; set; }
        public string txtHorarioLigacao { get; set; }
        public string txtTipoChamada { get; set; }
        public string txtGrupoHorarioTarifario { get; set; }
        public string txtDescricaoHorarioTarifario { get; set; }
        public string txtDegrauLigacao { get; set; }
        public string txtSinalValorLigacao { get; set; }
        public string txtAliquotaICMS { get; set; }
        public string txtValorLigacaoComImposto { get; set; }
        public string txtClasseServico { get; set; }
        public string txtFiller { get; set; }
    
        public virtual tblContasFebraban tblContasFebraban { get; set; }
    }
}
