//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContelBlockedStatus
    {
        public int intId { get; set; }
        public int intIdPerson { get; set; }
        public string txtLinha { get; set; }
        public Nullable<System.DateTime> dteBlocked { get; set; }
        public Nullable<System.DateTime> dteUnblocked { get; set; }
        public string txtStatus { get; set; }
        public bool bitAuto { get; set; }
    }
}
