//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComissionTokens
    {
        public int intIdToken { get; set; }
        public Nullable<System.Guid> guidToken { get; set; }
        public Nullable<int> intIdComissionOrder { get; set; }
        public Nullable<int> intIdCustomerReceiver { get; set; }
        public Nullable<int> intIdAgent { get; set; }
        public bool bitComissionConceded { get; set; }
        public System.DateTime dteLimit { get; set; }
        public System.DateTime dteCreated { get; set; }
        public Nullable<System.DateTime> dteConceded { get; set; }
    
        public virtual tblComissionOrder tblComissionOrder { get; set; }
        public virtual tblPersons tblPersons { get; set; }
    }
}
