//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCCRefusedLog
    {
        public int intId { get; set; }
        public int intIdPerson { get; set; }
        public string txtChargeIds { get; set; }
        public System.DateTime dteVigencia { get; set; }
        public System.DateTime dteCreate { get; set; }
        public Nullable<System.DateTime> dteLastUpdate { get; set; }
        public int intReminderCount { get; set; }
        public bool IsActive { get; set; }
    }
}
