//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContasFebraban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblContasFebraban()
        {
            this.tblBilhetacoesFebraban = new HashSet<tblBilhetacoesFebraban>();
            this.tblDescontosFebraban = new HashSet<tblDescontosFebraban>();
            this.tblEnderecosFebraban = new HashSet<tblEnderecosFebraban>();
            this.tblHeadsFebraban = new HashSet<tblHeadsFebraban>();
            this.tblResumosFebraban = new HashSet<tblResumosFebraban>();
            this.tblServicosFebraban = new HashSet<tblServicosFebraban>();
            this.tblTotalizadoresFebraban = new HashSet<tblTotalizadoresFebraban>();
        }
    
        public int intContaId { get; set; }
        public System.DateTime dteInsert { get; set; }
        public string dteGeracaoConta { get; set; }
        public int intTipoOperadora { get; set; }
        public string txtIdContaUnica { get; set; }
        public long intIdContaUnica { get; set; }
        public string txtEmissao { get; set; }
        public long intIdEmissao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBilhetacoesFebraban> tblBilhetacoesFebraban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDescontosFebraban> tblDescontosFebraban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEnderecosFebraban> tblEnderecosFebraban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHeadsFebraban> tblHeadsFebraban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblResumosFebraban> tblResumosFebraban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServicosFebraban> tblServicosFebraban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTotalizadoresFebraban> tblTotalizadoresFebraban { get; set; }
    }
}
