//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContasClaro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblContasClaro()
        {
            this.tblContasClaroLinhaRegistro = new HashSet<tblContasClaroLinhaRegistro>();
            this.tblContasClaroRegistroNotaFiscal = new HashSet<tblContasClaroRegistroNotaFiscal>();
        }
    
        public int intContaId { get; set; }
        public System.DateTime dteInsert { get; set; }
        public string txtIdContaUnica { get; set; }
        public string txtDataGeracaoArquivo { get; set; }
        public string txtIdentificadorEmpresa { get; set; }
        public string txtCodigoCliente { get; set; }
        public string txtNomeCliente { get; set; }
        public string txtEnderecoCliente { get; set; }
        public string txtVencimento { get; set; }
        public string txtDataReferenciaInicio { get; set; }
        public string txtDataReferenciaFim { get; set; }
        public string txtValor { get; set; }
        public string txtCodigoReferenciaDebitoAutomatico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContasClaroLinhaRegistro> tblContasClaroLinhaRegistro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContasClaroRegistroNotaFiscal> tblContasClaroRegistroNotaFiscal { get; set; }
    }
}
