//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContelTopupHistoryExcel
    {
        public int intId { get; set; }
        public string txtLinha { get; set; }
        public string txtTipo { get; set; }
        public System.DateTime dteDateRec { get; set; }
        public string txtName { get; set; }
        public string txtApelido { get; set; }
        public string txtValor { get; set; }
        public string txtValorPlano { get; set; }
        public string txtPlano { get; set; }
    }
}
