//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContelTopupHistory
    {
        public int intId { get; set; }
        public string txtLinha { get; set; }
        public string txtDataRecarga { get; set; }
        public string txtDataCadastro { get; set; }
        public string txtPlano { get; set; }
        public string txtValor { get; set; }
        public string txtValorPago { get; set; }
        public string txtFormaPagto { get; set; }
        public string txtSolicitadoPor { get; set; }
        public Nullable<System.DateTime> dteInsertTS { get; set; }
    }
}
