//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContelLinhasList
    {
        public int intId { get; set; }
        public string txtlinha { get; set; }
        public string txticcid { get; set; }
        public string txttitular { get; set; }
        public string txttitular_apelido { get; set; }
        public string txtdata_ex { get; set; }
        public string txtdata_portout { get; set; }
        public string txtnome_identificacao { get; set; }
        public string txtemoji { get; set; }
        public string txtdata_ativacao { get; set; }
        public string txtdata_inicio_plano { get; set; }
        public string txtdata_fim_plano { get; set; }
        public string txtdata_renovacao { get; set; }
        public string txtplano { get; set; }
        public string txtdocumento_titular { get; set; }
        public string txtstatus { get; set; }
        public string txtrecorrencia_cartao { get; set; }
        public string txtportin { get; set; }
        public string txtesim { get; set; }
        public string txtbloqueada { get; set; }
        public string txtrecarga_automatica { get; set; }
        public string txtrestante_dados { get; set; }
        public string txtdata_cancelamento_linha { get; set; }
        public string dteAutoTopup { get; set; }
        public Nullable<bool> bitRecAutoFC { get; set; }
    }
}
