//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommisionLevels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCommisionLevels()
        {
            this.tblComissionOrder = new HashSet<tblComissionOrder>();
        }
    
        public int intIdComission { get; set; }
        public int intLevel { get; set; }
        public int intAmount { get; set; }
        public bool bitActive { get; set; }
        public Nullable<System.DateTime> dteUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComissionOrder> tblComissionOrder { get; set; }
    }
}
