//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContasClaroRegistroNotaFiscal
    {
        public int intId { get; set; }
        public int intContaId { get; set; }
        public string txtNotaFiscal { get; set; }
        public string txtCodigo { get; set; }
        public string txtTipo { get; set; }
        public string txtAliquota { get; set; }
        public string txtBaseCalculo { get; set; }
        public string txtValorImposto { get; set; }
    
        public virtual tblContasClaro tblContasClaro { get; set; }
    }
}
