//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCheckoutPagarMeLog
    {
        public int intCheckoutLogId { get; set; }
        public Nullable<int> intAmount { get; set; }
        public Nullable<int> intDaysLimit { get; set; }
        public string txtBoletoInstructions { get; set; }
        public string txtNome { get; set; }
        public string txtEmail { get; set; }
        public string txtDocumentNumber { get; set; }
        public string txtStreet { get; set; }
        public string txtStreetNumber { get; set; }
        public string txtNeighborhood { get; set; }
        public string txtZipcode { get; set; }
        public string txtDdd { get; set; }
        public string txtNumber { get; set; }
        public string txtCardHolderName { get; set; }
        public string txtCardNumber { get; set; }
        public string txtCardExpirationDate { get; set; }
        public string txtCardCvv { get; set; }
        public string txtTransactionId { get; set; }
        public string txtLinkBoleto { get; set; }
        public Nullable<bool> bitCard { get; set; }
        public Nullable<bool> bitBoleto { get; set; }
        public Nullable<int> intTipoLog { get; set; }
        public Nullable<System.DateTime> dteRegistro { get; set; }
    }
}
