//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComissionOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblComissionOrder()
        {
            this.tblComissionTokens = new HashSet<tblComissionTokens>();
        }
    
        public int intIdComissionOrder { get; set; }
        public Nullable<int> intIdComission { get; set; }
        public Nullable<int> intIdBonus { get; set; }
        public int intIdTransaction { get; set; }
        public Nullable<int> intIdCustomerReceiver { get; set; }
        public Nullable<int> intIdAgent { get; set; }
        public bool bitComissionConceded { get; set; }
        public Nullable<System.DateTime> dteValidity { get; set; }
        public Nullable<System.DateTime> dteConceded { get; set; }
        public System.DateTime dteCreated { get; set; }
        public Nullable<int> intAmount { get; set; }
        public Nullable<int> intTotalLinhas { get; set; }
        public Nullable<int> intIdCustomerGiver { get; set; }
        public string txtIdTransaction { get; set; }
        public Nullable<int> intIdGateway { get; set; }
    
        public virtual tblBonusOptions tblBonusOptions { get; set; }
        public virtual tblCommisionLevels tblCommisionLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComissionTokens> tblComissionTokens { get; set; }
        public virtual tblPersons tblPersons { get; set; }
    }
}
