//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComissionValidationLog
    {
        public int intId { get; set; }
        public Nullable<int> intIdComission { get; set; }
        public Nullable<bool> bitComissionConceded { get; set; }
        public Nullable<bool> bitComissionDispatched { get; set; }
        public Nullable<int> intIdAgent { get; set; }
        public Nullable<System.DateTime> dteCreated { get; set; }
    }
}
