//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConfigSettings
    {
        public int intId { get; set; }
        public string txtConfigName { get; set; }
        public string txtConfigValue { get; set; }
        public Nullable<bool> bitIsActive { get; set; }
    }
}
