//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChargingHistory
    {
        public int intId { get; set; }
        public Nullable<int> intIdCustomer { get; set; }
        public Nullable<int> intIdCollector { get; set; }
        public string txtCollectorName { get; set; }
        public Nullable<int> intIdPaymentType { get; set; }
        public string txtComment { get; set; }
        public System.DateTime dtePayment { get; set; }
        public string txtAmmountPayment { get; set; }
        public string txtTokenTransaction { get; set; }
        public Nullable<long> intIdBoleto { get; set; }
        public string txtAcquireId { get; set; }
        public Nullable<System.DateTime> dteCreate { get; set; }
        public Nullable<System.DateTime> dteModify { get; set; }
        public Nullable<int> intPaymentStatus { get; set; }
        public string txtTransactionComment { get; set; }
        public Nullable<System.DateTime> dteDueDate { get; set; }
        public Nullable<int> PhoneId { get; set; }
        public Nullable<System.DateTime> dteChargingDate { get; set; }
        public string txtChargingComment { get; set; }
        public Nullable<int> validityMonth { get; set; }
        public Nullable<int> validityYear { get; set; }
        public Nullable<System.DateTime> dteValidity { get; set; }
        public Nullable<int> intChargeStatusId { get; set; }
        public Nullable<System.DateTime> dteCharge { get; set; }
        public Nullable<long> intIdTransaction { get; set; }
        public Nullable<bool> bitComissionConceded { get; set; }
        public Nullable<bool> bitCash { get; set; }
        public string txtCommentEmail { get; set; }
        public string txtCommentBoleto { get; set; }
        public Nullable<bool> bitCanceled { get; set; }
        public string txtPaymentId { get; set; }
        public Nullable<int> intIdGateway { get; set; }
        public Nullable<bool> bitComissionInapt { get; set; }
        public string txtCartHash { get; set; }
        public Nullable<bool> bitPago { get; set; }
        public string txtStatusPaymentLoja { get; set; }
        public Nullable<int> intIdCheckoutLoja { get; set; }
        public Nullable<int> intIdFrete { get; set; }
        public Nullable<bool> bitDescontoConcedido { get; set; }
        public string pixCode { get; set; }
        public Nullable<bool> bitActive { get; set; }
        public Nullable<System.DateTime> dteExpiryDate { get; set; }
        public string txtWAPhones { get; set; }
        public bool bitSendWAText { get; set; }
        public Nullable<bool> bitSendMarketing1 { get; set; }
        public Nullable<bool> bitSendMarketing2 { get; set; }
        public string txtboletoUrl { get; set; }
        public string txtboletoBarcode { get; set; }
        public Nullable<int> intInstallments { get; set; }
        public string txtInstaRegsiterData { get; set; }
    
        public virtual tblPersons tblPersons { get; set; }
        public virtual tblPaymentTypes tblPaymentTypes { get; set; }
        public virtual tblPersonsPhones tblPersonsPhones { get; set; }
    }
}
