//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDrCelularTemp
    {
        public int intId { get; set; }
        public string txtLinha { get; set; }
        public string txtValorTotalFatura { get; set; }
        public string txtUsoLinha { get; set; }
        public string txtOperadora { get; set; }
        public string txtCliente { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<int> ano { get; set; }
        public string txtPlanoDeServico { get; set; }
        public string txtCentroDeCusto { get; set; }
        public string txtUsuario { get; set; }
        public string txtFuncionalidade { get; set; }
        public string txtEmpresa { get; set; }
        public string txtPeriodo { get; set; }
        public string txtFatura { get; set; }
        public Nullable<int> txtNumberPhones { get; set; }
        public string txtOperadoraButton { get; set; }
    }
}
