//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDescontosFebraban
    {
        public int intId { get; set; }
        public Nullable<int> intContaId { get; set; }
        public string txtControleSequencial { get; set; }
        public string txtVencimento { get; set; }
        public string txtEmissao { get; set; }
        public string txtIDUnicoNRC { get; set; }
        public string txtRecursoCNL { get; set; }
        public string txtDDD { get; set; }
        public string txtNumeroTelefone { get; set; }
        public string txtGrupoCategoria { get; set; }
        public string txtDescricaoGrupoCategoria { get; set; }
        public string txtSinalValorLigacao { get; set; }
        public string txtBaseCalculoDesconto { get; set; }
        public string txtPercentualDesconto { get; set; }
        public string txtValorLigacao { get; set; }
        public string txtDataInicioAcerto { get; set; }
        public string txtHoraInicioAcerto { get; set; }
        public string txtDataFimAcerto { get; set; }
        public string txtHoraFimAcerto { get; set; }
        public string txtClasseServico { get; set; }
        public string txtFiller { get; set; }
    
        public virtual tblContasFebraban tblContasFebraban { get; set; }
    }
}
