//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblESimICCIDPool
    {
        public int intId { get; set; }
        public int intIdContel { get; set; }
        public bool bitValidated { get; set; }
        public string txtICCID { get; set; }
        public string txtTipo { get; set; }
        public string txtActivationCodeLPA { get; set; }
        public bool bitActivated { get; set; }
        public System.DateTime dteInsert { get; set; }
        public System.DateTime dteUpdate { get; set; }
        public Nullable<int> intIdPersonActivated { get; set; }
        public Nullable<System.DateTime> dteActivated { get; set; }
    }
}
