//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbleSimActivationInfo
    {
        public int intId { get; set; }
        public string txtLinha { get; set; }
        public string txtICCID { get; set; }
        public string txtActivationCode { get; set; }
        public string txtActivationPdfUrl { get; set; }
        public string txtActivationImage { get; set; }
        public string txtActivationDate { get; set; }
        public string txtPlano { get; set; }
        public Nullable<System.DateTime> dteInsert { get; set; }
    }
}
