//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnderecosFebraban
    {
        public int intId { get; set; }
        public Nullable<int> intContaId { get; set; }
        public string txtControleSequencial { get; set; }
        public string txtIDUnicoNRC { get; set; }
        public string txtDDD { get; set; }
        public string txtNumeroTelefone { get; set; }
        public string txtCaracteristicaRecurso { get; set; }
        public string txtCNLRecursoEnderecoPontaA { get; set; }
        public string txtNomeLocalidadePontaA { get; set; }
        public string txtUFLocalidadePontaA { get; set; }
        public string txtEnderecoPontaA { get; set; }
        public string txtNumeroEnderecoPontaA { get; set; }
        public string txtComplementoPontaA { get; set; }
        public string txtBairroPontaA { get; set; }
        public string txtCNLRecursoEnderecoPontaB { get; set; }
        public string txtNomeLocalidadePontaB { get; set; }
        public string txtUFLocalidadePontaB { get; set; }
        public string txtEnderecoPontaB { get; set; }
        public string txtNumeroEnderecoPontaB { get; set; }
        public string txtComplementoPontaB { get; set; }
        public string txtBairroPontaB { get; set; }
        public string txtFiller { get; set; }
    
        public virtual tblContasFebraban tblContasFebraban { get; set; }
    }
}
