//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmailTemplates
    {
        public int intId { get; set; }
        public string txtTipoTemplate { get; set; }
        public string txtDescription { get; set; }
        public string txtSubject { get; set; }
        public string toEmail { get; set; }
        public string cc { get; set; }
        public string bcc { get; set; }
        public string fromEmail { get; set; }
        public Nullable<bool> bitAtivo { get; set; }
        public Nullable<bool> bitShowAction { get; set; }
    }
}
