//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFoneclubePagarmeTransactions
    {
        public int intId { get; set; }
        public string txtOutdadetStatus { get; set; }
        public Nullable<int> intRefuse_reason { get; set; }
        public string txtStatus_reason { get; set; }
        public string txtAcquirer_name { get; set; }
        public string txtAcquirer_id { get; set; }
        public Nullable<int> intTid { get; set; }
        public Nullable<int> intNsu { get; set; }
        public Nullable<System.DateTime> dteDate_created { get; set; }
        public Nullable<System.DateTime> dteDate_updated { get; set; }
        public Nullable<int> intAmount { get; set; }
        public Nullable<int> intAuthorized_amount { get; set; }
        public Nullable<int> intPaid_amount { get; set; }
        public Nullable<int> intRefunded_amount { get; set; }
        public Nullable<int> intInstallments { get; set; }
        public Nullable<long> intIdTransaction { get; set; }
        public Nullable<int> intCost { get; set; }
        public string txtCard_holder_name { get; set; }
        public string txtCard_last_digits { get; set; }
        public string txtCard_first_digits { get; set; }
        public string txtCard_brand { get; set; }
        public string txtBoleto_url { get; set; }
        public string txtBoleto_barcode { get; set; }
        public Nullable<System.DateTime> dteBoleto_expiration_date { get; set; }
        public string txtIp { get; set; }
        public Nullable<int> intIdCustomer { get; set; }
        public string txtPayment_method { get; set; }
        public Nullable<bool> bitComissionRevision { get; set; }
        public string txtPixCode { get; set; }
        public Nullable<System.DateTime> dtePix_expiration_date { get; set; }
    }
}
