//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGenericFlags
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGenericFlags()
        {
            this.tblGenericPhoneFlags = new HashSet<tblGenericPhoneFlags>();
        }
    
        public int intId { get; set; }
        public string txtFlagDescription { get; set; }
        public Nullable<bool> bitExternalFlag { get; set; }
        public Nullable<bool> bitPhoneFlag { get; set; }
        public Nullable<int> intIdEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGenericPhoneFlags> tblGenericPhoneFlags { get; set; }
    }
}
