//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHeadsFebraban
    {
        public int intId { get; set; }
        public Nullable<int> intContaId { get; set; }
        public string txtControleSequencial { get; set; }
        public string txtIdContaUnica { get; set; }
        public string txtDataGeracaoArquivo { get; set; }
        public string txtIdentificadorEmpresa { get; set; }
        public string txtEmpresaUF { get; set; }
        public string txtCodigoCliente { get; set; }
        public string txtNomeCliente { get; set; }
        public string txtClienteCGC { get; set; }
        public string txtVencimento { get; set; }
        public string txtEmissao { get; set; }
        public string txtFiller { get; set; }
    
        public virtual tblContasFebraban tblContasFebraban { get; set; }
    }
}
