//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInternationActivationPool
    {
        public int intId { get; set; }
        public Nullable<int> intRequiredSale { get; set; }
        public Nullable<int> intRequiredTopup { get; set; }
        public int intIdPerson { get; set; }
        public string txtPhoneNumber { get; set; }
        public string txtICCID { get; set; }
        public string txtStatus { get; set; }
        public string txtResetStatus { get; set; }
        public string txtResetICCID { get; set; }
        public bool bitReadyForReActivation { get; set; }
        public System.DateTime dteActivation { get; set; }
        public Nullable<System.DateTime> dteReset { get; set; }
        public Nullable<int> intIdPersonReset { get; set; }
        public Nullable<int> intIdPlan { get; set; }
        public Nullable<bool> bitFailedPostActivation { get; set; }
    }
}
