//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInternationalDeposits
    {
        public int intId { get; set; }
        public int intIdPerson { get; set; }
        public System.DateTime dteDateAdded { get; set; }
        public decimal intUSDAmount { get; set; }
        public decimal intBRAmount { get; set; }
        public decimal txtConversionRate { get; set; }
        public string intIdPaymentType { get; set; }
        public string txtCCCharges { get; set; }
        public string txtBankCharges { get; set; }
        public string txtHandlingCharges { get; set; }
        public Nullable<decimal> intFinalValue { get; set; }
        public string txtComment { get; set; }
        public Nullable<bool> bitRefund { get; set; }
    
        public virtual tblPersons tblPersons { get; set; }
    }
}
