//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIntlFailedActivations
    {
        public int intId { get; set; }
        public int intIdPerson { get; set; }
        public string txtPhone { get; set; }
        public string txtICCID { get; set; }
        public System.DateTime dteDate { get; set; }
        public bool IsRefunded { get; set; }
        public string txtComments { get; set; }
    }
}
