//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogComissionOrder
    {
        public int intIdTipo { get; set; }
        public System.DateTime dteRegister { get; set; }
        public Nullable<bool> bitSucesso { get; set; }
        public Nullable<int> intTotalOrdensLiberadas { get; set; }
    }
}
