//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public int intId { get; set; }
        public Nullable<int> intIdTipo { get; set; }
        public string txtAction { get; set; }
        public System.DateTime dteTimeStamp { get; set; }
    
        public virtual tblLogTipo tblLogTipo { get; set; }
    }
}
