//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhoneStock
    {
        public int intId { get; set; }
        public string txtNumero { get; set; }
        public string txtCNPJ { get; set; }
        public string txtRazaoSocial { get; set; }
        public string txtCodCliente { get; set; }
        public string txtICCID { get; set; }
        public string txtNumeroTemporario { get; set; }
        public Nullable<System.DateTime> dteRegistroEntrada { get; set; }
        public Nullable<System.DateTime> dteRegistroSaida { get; set; }
        public Nullable<System.DateTime> dteReferencia { get; set; }
        public string txtCodigoFatura { get; set; }
    }
}
