//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhones
    {
        public int intIdPhone { get; set; }
        public int intDDD { get; set; }
        public int intNumber { get; set; }
        public string txtICCID { get; set; }
    }
}
