//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlansOptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlansOptions()
        {
            this.tblPlans = new HashSet<tblPlans>();
        }
    
        public int intIdPlan { get; set; }
        public int intIdOperator { get; set; }
        public string txtDescription { get; set; }
        public int intCost { get; set; }
        public Nullable<bool> intBitActive { get; set; }
        public string txtDescriptionAmigavel { get; set; }
        public string txtDescriptionResumo { get; set; }
        public Nullable<int> intOperatorPlanId { get; set; }
    
        public virtual tblOperadoras tblOperadoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlans> tblPlans { get; set; }
    }
}
