//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhonePropertyHistory
    {
        public int intIdHistory { get; set; }
        public Nullable<int> intIdPerson { get; set; }
        public Nullable<System.DateTime> dteChange { get; set; }
        public Nullable<int> intIdOperator { get; set; }
        public Nullable<int> intIdPlan { get; set; }
        public Nullable<double> intPlanPrice { get; set; }
        public Nullable<int> intIdPhone { get; set; }
        public Nullable<int> intPhoneNumber { get; set; }
        public Nullable<int> intPhoneDDD { get; set; }
        public Nullable<int> intEventType { get; set; }
        public Nullable<int> intIdStatus { get; set; }
        public Nullable<System.DateTime> dteEntrada { get; set; }
        public Nullable<System.DateTime> dteSaida { get; set; }
    }
}
