//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhonesStockProperty
    {
        public int intId { get; set; }
        public string txtPhone { get; set; }
        public string txtProperty { get; set; }
        public Nullable<int> intIdProperty { get; set; }
        public Nullable<int> intIdOperadora { get; set; }
        public string txtDescricaoOperadora { get; set; }
        public System.DateTime dteRegister { get; set; }
    }
}
