//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlanDetails
    {
        public int intIdPlanDetail { get; set; }
        public int intIdPlan { get; set; }
        public int intDetailType { get; set; }
        public long intDetailValue { get; set; }
        public long intDetailCost { get; set; }
        public long intExtraCost { get; set; }
    }
}
