//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonsPhones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPersonsPhones()
        {
            this.tblLineRecord = new HashSet<tblLineRecord>();
            this.tblPhonesServices = new HashSet<tblPhonesServices>();
            this.tblChargingHistory = new HashSet<tblChargingHistory>();
            this.tblChargingScheduled = new HashSet<tblChargingScheduled>();
        }
    
        public int intId { get; set; }
        public Nullable<int> intIdPerson { get; set; }
        public Nullable<int> intDDD { get; set; }
        public Nullable<long> intPhone { get; set; }
        public Nullable<int> intIdOperator { get; set; }
        public Nullable<bool> bitPhoneClube { get; set; }
        public Nullable<int> intIdPlan { get; set; }
        public string txtNickname { get; set; }
        public Nullable<bool> bitPortability { get; set; }
        public Nullable<bool> bitAtivo { get; set; }
        public Nullable<System.DateTime> dteEntradaLinha { get; set; }
        public Nullable<System.DateTime> dteSaidaLinha { get; set; }
        public Nullable<bool> bitDono { get; set; }
        public Nullable<int> intIdStatus { get; set; }
        public Nullable<int> intAmmoutPrecoVip { get; set; }
        public Nullable<bool> bitPrecoVip { get; set; }
        public Nullable<bool> bitDelete { get; set; }
        public Nullable<bool> bitBonusConceded { get; set; }
        public Nullable<int> intCountryCode { get; set; }
        public Nullable<int> intContactType { get; set; }
        public Nullable<bool> bitAmigos { get; set; }
        public Nullable<bool> bitDescontoConcedido { get; set; }
        public Nullable<bool> bitDescontoOrdenado { get; set; }
        public string txtICCID { get; set; }
        public string txtPortNumber { get; set; }
        public Nullable<bool> bitEsim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLineRecord> tblLineRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhonesServices> tblPhonesServices { get; set; }
        public virtual tblPersons tblPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChargingHistory> tblChargingHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChargingScheduled> tblChargingScheduled { get; set; }
    }
}
