//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhonesServices
    {
        public int intId { get; set; }
        public Nullable<int> intIdPhone { get; set; }
        public Nullable<int> intIdService { get; set; }
        public Nullable<bool> bitAtivo { get; set; }
        public Nullable<System.DateTime> dteUpdate { get; set; }
        public Nullable<System.DateTime> dteAtivacao { get; set; }
        public Nullable<System.DateTime> dteDesativacao { get; set; }
    
        public virtual tblServices tblServices { get; set; }
        public virtual tblPersonsPhones tblPersonsPhones { get; set; }
    }
}
