//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonsParents
    {
        public int intId { get; set; }
        public Nullable<int> intDDDParent { get; set; }
        public Nullable<long> intPhoneParent { get; set; }
        public string txtNameParent { get; set; }
        public Nullable<int> intIdSon { get; set; }
        public Nullable<System.DateTime> dteCadastro { get; set; }
        public Nullable<int> intIdParent { get; set; }
    }
}
