//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegisterCustomersLog
    {
        public int intIdCustomer { get; set; }
        public System.DateTime dteRegister { get; set; }
        public System.Guid guidId { get; set; }
        public string txtPhone { get; set; }
        public string txtName { get; set; }
        public string txtEmail { get; set; }
        public string txtDocument { get; set; }
        public Nullable<int> intDocumentType { get; set; }
        public string txtPassword { get; set; }
        public Nullable<int> idPai { get; set; }
        public string txtLog { get; set; }
    }
}
