//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResumosFebraban
    {
        public int intId { get; set; }
        public Nullable<int> intContaId { get; set; }
        public string txtControleSequencial { get; set; }
        public string txtVencimento { get; set; }
        public string txtEmissao { get; set; }
        public string txtIDUnicoNRC { get; set; }
        public string txtRecursoCNL { get; set; }
        public string txtLocalidade { get; set; }
        public string txtDDD { get; set; }
        public string txtNumeroTelefone { get; set; }
        public string txtTipoServico { get; set; }
        public string txtDescricaoServico { get; set; }
        public string txtCaracteristicaRecurso { get; set; }
        public string txtDegrauRecurso { get; set; }
        public string txtVelocidadeRecurso { get; set; }
        public string txtUnidadeVelocidadeRecurso { get; set; }
        public string txtInicioAssinatura { get; set; }
        public string txtFimAssinatura { get; set; }
        public string txtInicioPeriodoServico { get; set; }
        public string txtFimPeriodoServico { get; set; }
        public string txtUnidadeConsumo { get; set; }
        public string txtQuantidadeConsumo { get; set; }
        public string txtSinalValorConsumo { get; set; }
        public string txtValorConsumo { get; set; }
        public string txtSinalAssinatura { get; set; }
        public string txtValorAssinatura { get; set; }
        public string txtAliquota { get; set; }
        public string txtSinalICMS { get; set; }
        public string txtValorICMS { get; set; }
        public string txtSinalTotalOutrosImpostos { get; set; }
        public string txtValorTotalImpostos { get; set; }
        public string txtNumeroNotaFiscal { get; set; }
        public string txtSinalValorConta { get; set; }
        public string txtValorConta { get; set; }
        public string txtFiller { get; set; }
    
        public virtual tblContasFebraban tblContasFebraban { get; set; }
    }
}
