//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShopifySalesInfo
    {
        public int intId { get; set; }
        public int intIdPerson { get; set; }
        public string txtShopifyOrderId { get; set; }
        public string txtShopifyOrderLineId { get; set; }
        public long intShopifyCustId { get; set; }
        public string txtShopifyEmail { get; set; }
        public string txtComment { get; set; }
        public string txtSku { get; set; }
        public int intIdPlan { get; set; }
        public string txtPrice { get; set; }
        public string txtActivationCode { get; set; }
        public string txtActivationQrCode { get; set; }
        public string txtActivationPDFLink { get; set; }
        public string txtPhone { get; set; }
        public string txtICCID { get; set; }
        public string txtDateActivation { get; set; }
        public string txtOrderUIPath { get; set; }
        public System.DateTime dteInsert { get; set; }
    }
}
