//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStoreOrders
    {
        public long intOrderId { get; set; }
        public System.DateTime dteOrderDate { get; set; }
        public int intNumberOfPlans { get; set; }
        public int txtTotal { get; set; }
        public string txtPaymentStatus { get; set; }
        public string txtStatus { get; set; }
        public Nullable<long> intIdTransaction { get; set; }
        public int intIdCharge { get; set; }
        public int intIdPerson { get; set; }
    }
}
