//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserSettings
    {
        public int intPerson { get; set; }
        public bool bitPrecoPromoSum { get; set; }
        public bool bitPrecoFCSum { get; set; }
        public bool bitUse2Prices { get; set; }
        public bool bitVIP { get; set; }
        public bool bitLinhaAtiva { get; set; }
        public bool bitShowICCID { get; set; }
        public bool bitShowPort { get; set; }
    }
}
