//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWhatsAppStatus
    {
        public int intId { get; set; }
        public Nullable<int> intIdCharge { get; set; }
        public Nullable<int> intIdPerson { get; set; }
        public Nullable<System.DateTime> dteMsgSentDateTime { get; set; }
        public Nullable<System.DateTime> dteMsgReceivedDateTime { get; set; }
        public Nullable<System.DateTime> dteMsgReadDateTime { get; set; }
        public Nullable<int> intStatus { get; set; }
        public string txtPhoneNumber { get; set; }
        public string intIdChat { get; set; }
    }
}
