//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWhatsappMessages
    {
        public long intIdMessage { get; set; }
        public long intIdClient { get; set; }
        public string txtText { get; set; }
        public string txtType { get; set; }
        public string txtPdf { get; set; }
        public System.DateTime dteCreated { get; set; }
        public string txtSendBy { get; set; }
        public bool bitRead { get; set; }
    }
}
