//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWhatsAppMessageTemplates
    {
        public int intId { get; set; }
        public string txtTrigger { get; set; }
        public string txtComment { get; set; }
        public string txtTitle { get; set; }
        public string txtFooter { get; set; }
        public string txtButtons { get; set; }
        public string txtMessageType { get; set; }
        public string txtCallBackAction { get; set; }
        public string txtTemplateName { get; set; }
        public Nullable<bool> bitInternal { get; set; }
        public string txtCommentTemp { get; set; }
        public string txtUrls { get; set; }
        public string txtListButton { get; set; }
        public string txtListSections { get; set; }
        public string txtListSectionRows { get; set; }
    }
}
